name: Run Postman Collection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Newman (Postman CLI)
        run: npm install -g newman

      - name: Run Postman Collection
        run: |
          newman run SAM.postman_collection.json  
